### ISSUE TITLE
How to import this exactly?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [hitanshu-dhawan/McCompose#16]
Only canary still supports Compose, so that's where I tried:
Android Studio Arctic Fox | 2020.3.1 Canary 5
Build #AI-203.6682.168.2031.7101492, built on January 25, 2021
Runtime version: 11.0.8+10-b944.6842174 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 8048M
Cores: 12
Registry: external.system.auto.import.disabled=true, ide.settings.move.mouse.on.default.button=true, debugger.watches.in.variables=false
Non-Bundled Plugins: String Manipulation, izhangzhihao.rainbow.brackets, org.intellij.plugins.markdown

But then I got this when opening the project:

```
The project is using an incompatible version (7.0.0-alpha02) of the Android Gradle plugin.
Upgrade to the latest version
```

And when I try to continue, it fails...

[video.zip](https://github.com/hitanshu-dhawan/McCompose/files/5982593/video.zip)

**Comment by hitanshu-dhawan** [comment]
Hey, this error usually occurs when using incompatible version of Android Studio.

I've updated the project to Jetpack Compose 1.0.0-beta01.
Make sure you use Android Studio Arctic Fox Canary 8 (2020.3.1.8) for this project to work.

**Comment by AndroidDeveloperLB** [comment]
Tried now on an even newer version:

Android Studio Arctic Fox | 2020.3.1 Canary 9
Build #AI-203.7148.57.2031.7185775, built on March 5, 2021
Runtime version: 11.0.8+10-b944.6842174 amd64
VM: OpenJDK 64-Bit Server VM by N/A
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4000M
Cores: 12
Registry: external.system.auto.import.disabled=true, ide.settings.move.mouse.on.default.button=true, debugger.watches.in.variables=false
Non-Bundled Plugins: String Manipulation, com.google.mad-scorecard, org.intellij.plugins.markdown

And it still doesn't work.
See attached:

[lkIzPIjkYe.zip](https://github.com/hitanshu-dhawan/McCompose/files/6111868/lkIzPIjkYe.zip)

**Comment by AndroidDeveloperLB** [comment]
@hitanshu-dhawan Guys I got the newest one. Why can't it open previous ones? Why can't it auto-fix what's needed to make it possible? It says it's about to update, but still fails.
This repository even puts all dependencies versions in a special file.
Why does Android Studio offer to update it for me, if it keeps failing?

Anyway, I've done this manually and now it works.
Thanks.
